### ISSUE TITLE
how to remove SSL for the  UI ?

### ISSUE THREAD

**Issue by raykai** [stokes84/ConfigServer-Firewall-Installer#1]
im trying to find info of how to remove the SSL for going in the UI and how to change the SSL for a new one i did i typo on it

**Comment by stokes84** [comment]
`/etc/csf/csf.conf` starts at line 1768. Sorry there's no option within CSF to disable SSL in the UI. Make sure you have your SSL cert (.crt) and key (.key) in `/etc/csf/ui`.
